[tool.poetry]
name = "mental-gym"
version = "0.1.0"
description = "Build technical fluency through deliberate practice and first-principles implementation."
authors = ["hy"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.2.2"
black = "^24.4.2"
flake8 = "^7.1.0"
isort = "^5.13.2"
docformatter = "^1.7.5"
pre-commit = "^3.7.1"
numpy = "^2.0.1"
colorama = "^0.4.6"
sortedcontainers = "^2.4.0"
scikit-learn = ">=1.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[tool.pytest.ini_options]
pythonpath = ["src/kattis/python", "src/leetcode/arrays_hashing", "src/leetcode/two_pointers", "src/leetcode/sliding_window", "src/leetcode/stack"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
